creating an active order the real one I promise
AtriEx/ATX pull request #113
Opened 2024-03-28 22:26 UTC by evanFroelich

ported over steubs code into a new branch to avoid merge hell.

2024-04-02 02:37 UTC, dylhack requested changes
left review comments in channel

2024-04-02 14:41 UTC, AltF02 requested changes
This code was written from memory so might not pass requirements or syntax checks. Hope this helps. I also only really looked at the `create_active_order.py` route. If you would like me to take a look at the other code, lmk :). If you think that its unnecessary then disregard my comments

2024-04-02 14:41 UTC, AltF02 commented on backend/routes/create_active_order.py
> +        return "Stock not found"
consider using an array instead of just returning a single error:

```suggestion
    errors = []
    if price < 1:
        errors.append("Price must be greater than 0")
    if quantity < 1:
        errors.append("Quantity must be greater than 0")
    if expirey < datetime.now(timezone.utc):
        errors.append("Expirey date cannot be in the past")
    if not supabase_middleman.fetch_stock_price(stock_id):
        errors.append("Stock not found")
    if errors:
        return ", ".join(errors)
```

2024-04-02 14:41 UTC, AltF02 commented on backend/routes/create_active_order.py
> +        return "Expirey date cannot be in the past"
Typo: expiry

2024-04-02 14:41 UTC, AltF02 commented on backend/routes/create_active_order.py
> +        return "Stock not found"
Avoid commenting out code and committing it to your source control system. When another developer sees your commented out code it can lead to confusion. Commented out code also tends to build up as developers are often scared to delete it thinking it must be important or related to another team member’s work.

Simply delete the line of code instead of commenting it out. Your repository has a history and getting the deleted line back should not be difficult if you need it again.

- https://bytedev.medium.com/code-comment-anti-patterns-and-why-the-comment-you-just-wrote-is-probably-not-needed-919a92cf6758

2024-04-02 14:41 UTC, AltF02 commented on backend/routes/create_active_order.py
> +            return "Insufficient quantity"
Consider delegating the validation to seperate functions:

```py
def validate_user(user_id):
    try:
        UUID(hex=user_id)
        user_profile = supabase_middleman.get_user_profile(user_id)
        if not user_profile:
            return "User not found"
    except ValueError:
        return "user_id is not in valid UUID format"
    return user_profile

def validate_stock(user_id, stock_id, buy_or_sell):
    if buy_or_sell:
        user_profile = validate_user(user_id)
        if not user_profile:
            return "User not found"
        if user_profile["balance"] < price * quantity:
            return "Insufficient balance"
    else:
        portfolio = supabase_middleman.get_user_portfolio(user_id)[stock_id]
        if not portfolio:
            return "Stock not found in users portfolio"
        if portfolio["quantity"] < 1:
            return "User does not own stock"
        if portfolio["quantity"] < quantity:
            return "Insufficient quantity"
    return True
```

```suggestion
    stock_validation = validate_stock(user_id, stock_id, buy_or_sell)
    if not stock_validation:
        return stock_validation

    user_profile = validate_user(user_id)
    if not user_profile:
        return user_profile
```

2024-04-02 14:41 UTC, AltF02 commented on backend/routes/create_active_order.py
> +    expirey = datetime.fromisoformat(expirey)  # Convert expirey to datetime object
Typo

2024-04-02 14:41 UTC, AltF02 commented on backend/routes/create_active_order.py
> +    return "Active order created"
Use dictionary unpacking instead:

```suggestion
    entries = [
        {
            "time_posted": time_posted,
            "buy_or_sell": buy_or_sell,
            "price": price,
            "expiry": str(expiry),
            "quantity": 1,
            "stockId": stock_id,
            "userId": user_id,
            "orderId": generated_order_id,
            "has_been_processed": False,
        }
        for _ in range(quantity)
    ]
    supabase_middleman.insert_entry("active_buy_sell", entries)
    return "Active order created"
```

2024-04-02 23:30 UTC, evanFroelich commented on backend/routes/create_active_order.py
> +        return "Expirey date cannot be in the past"
this typo also made it to the db a while back. this is fixed and the db will be next.

2024-04-02 23:34 UTC, evanFroelich commented on backend/routes/create_active_order.py
> +    expirey = datetime.fromisoformat(expirey)  # Convert expirey to datetime object
Mostly fixed. The database also has the typo so that will persist until this is merged and I can do a full pass on the db.

2024-04-02 23:38 UTC, evanFroelich commented on backend/routes/create_active_order.py
> +    return "Active order created"
That is a pretty clever trick I didnt know existed. Merged in.

2024-04-03 00:30 UTC, evanFroelich commented on backend/routes/create_active_order.py
> +            return "Insufficient quantity"
the validation functions you propose either return strings or an object or a bool. unsure if that was a mistake or not.

2024-04-08 16:10 UTC, dylhack requested changes
just one thing and I think its good to go. cc @AltF02

2024-04-08 16:10 UTC, dylhack commented on backend/routes/create_active_order.py
> +        return ", ".join(errors)
I really think this should raise an HTTP exception to let the client know something went wrong (ie).

```py
        raise HTTPException(status.HTTP_400_BAD_REQUEST, errors)
```

2024-04-08 16:22 UTC, evanFroelich commented on backend/routes/create_active_order.py
> +        return ", ".join(errors)
currently had to ditch the http exceptions as the original author couldnt finish the pr and the http exceptions he implemented were throwing errors that I was unable to debug. so for now this matches the other api endpoints with string returns until we can do a sweeping http exception overhaul later.

2024-04-08 16:27 UTC, dylhack approved these changes

2024-04-08 23:43 UTC, merged