Profile page
AtriEx/ATX pull request #5
Opened 2024-02-05 03:43 UTC by RubenOlano

A lot of updates base on shadcn rn. Super rough rn till we get more designs in

2024-02-05 16:43 UTC, sakulstar commented
Letting you know that you might have to redo some of the layout to make it fit with the [Website-Header branch](https://github.com/AtriEx/ATX/tree/Website-Header)

2024-02-05 22:26 UTC, quabey requested changes

2024-02-05 22:26 UTC, quabey commented on frontend/src/routes/profile/+page.svelte
> +	}
move this to a separate component so it can be reused in the future

2024-02-05 22:26 UTC, quabey commented on frontend/src/routes/profile/[username]/+page.server.ts
> +	if (username === '') throw error(404, 'User not found');
Add better checking if username is correct

2024-02-05 22:26 UTC, quabey commented on frontend/src/routes/profile/[username]/+page.server.ts
> +	if (username === '') throw error(404, 'User not found');
the error() function isnt thrown only called

2024-02-05 22:26 UTC, quabey commented on frontend/src/routes/profile/[username]/+page.server.ts
> +	};
get from DB

2024-02-05 22:26 UTC, quabey commented on frontend/src/routes/profile/[username]/+page.svelte
> +	}
use separate component

2024-02-05 22:26 UTC, quabey commented on frontend/src/routes/profile/[username]/+page.svelte
> +				</Dialog.Root>
login isnt part of this ticket, and also needs to be in a separate global component so it can be called from anywhere

2024-02-05 22:26 UTC, quabey commented on frontend/src/routes/profile/[username]/+page.svelte
> +				<h1 class="text-xl md:text-3xl font-bold text-violet-700">{profile.username}</h1>
show badges here https://www.shadcn-svelte.com/docs/components/badge
use hover card to show description https://www.shadcn-svelte.com/docs/components/hover-card

2024-02-05 22:26 UTC, quabey commented on frontend/src/routes/profile/[username]/+page.svelte
> +			</div>
show achievements here

2024-02-05 22:26 UTC, quabey commented on frontend/tailwind.config.js
> +				'dark-accent': '#00abc2'
Please use the color theme

2024-02-05 22:26 UTC, quabey commented on frontend/src/routes/profile/[username]/+page.svelte
> +		</div>
also show users balance

2024-02-05 22:26 UTC, quabey commented on frontend/package.json
> +		"@supabase/supabase-js": "^2.39.3",
Remove duplicate

2024-02-05 22:26 UTC, quabey commented on frontend/src/app.d.ts
> +		// interface Locals {}
why did you remove this ?

2024-02-05 22:26 UTC, quabey commented on frontend/src/lib/components/RewardButton.svelte
> +<script lang="ts">
where is this used ?

2024-02-05 22:26 UTC, quabey commented on frontend/src/routes/profile/[username]/+page.server.ts
> +	const data = await parent();
what is this for / where is it used ?

2024-02-06 00:00 UTC, RubenOlano commented on frontend/src/app.d.ts
> +		// interface Locals {}
This was removed because we're no longer adding these into the local object so it throws an error when trying to use the functions/properties

2024-02-06 00:01 UTC, RubenOlano commented on frontend/src/lib/components/RewardButton.svelte
> +<script lang="ts">
This is used in the user's profile to claim the reward. No real functionality yet

2024-02-06 00:02 UTC, RubenOlano commented on frontend/src/routes/profile/[username]/+page.server.ts
> +	const data = await parent();
This was used to fetch the user's profile from the `+layout.server.ts` in the `+page.server.ts`.

2024-02-06 00:05 UTC, quabey commented on frontend/src/lib/components/RewardButton.svelte
> +<script lang="ts">
what reward ?

2024-02-06 00:10 UTC, quabey commented on frontend/src/lib/components/RewardButton.svelte
> +<script lang="ts">
oh but why is that in the profile, and not just a button in the header ?

2024-02-06 00:13 UTC, RubenOlano commented on frontend/src/lib/components/RewardButton.svelte
> +<script lang="ts">
It was one of the requirements in the trello ticket before i realized it was gonna be in the header. I can remove it from this ticket if we need

2024-02-06 00:19 UTC, quabey commented on frontend/src/lib/components/RewardButton.svelte
> +<script lang="ts">
I think header would be easier for the user to access.

2024-02-06 17:28 UTC, quabey requested changes

2024-02-06 17:28 UTC, quabey commented on frontend/src/routes/profile/[username]/+page.server.ts
> +	const achievements = flags?.filter((flag) => flag.type === 'achievement') || [];
This is showing every stock and every flag, you need to get the flags and stocks in the user query
```js
const { data } = await adminSupabase
		.from('profiles')
		.select(
			`userId, 
			username, 
			portfolio(stockId, quantity, stockInfo(name))
			flags(name, image, description, type)
			`
		)
		.eq('username', params.username)
		.single()
		.throwOnError();
```

2024-02-06 17:28 UTC, quabey commented on frontend/src/routes/profile/[username]/+page.svelte
> +<ProfileComponent {...profile} />
why have this as an component ?

2024-02-06 17:28 UTC, quabey commented on frontend/tailwind.config.js
>  export default {
please look at how the how the colors are used and how cards are done on the theme we picked
https://www.realtimecolors.com/?colors=e9fbfc-010104-31c4d8-315054-00abc2&fonts=Poppins-Lato
https://tailwindcss.com/docs/opacity
![image](https://github.com/AtriEx/ATX/assets/50772988/58a75143-a095-45c5-ab53-38f9c9418079)

2024-02-06 17:28 UTC, quabey commented on frontend/src/routes/profile/[username]/+page.server.ts
> +		.select()
Please limit the query to only things you need

2024-02-06 17:28 UTC, quabey commented on frontend/src/routes/profile/+layout.server.ts
> +	throw redirect(303, `/profile/${profile.username}`);
this doesnt work, remove it for now, until we have the login and user object store setup

2024-02-06 17:28 UTC, quabey commented on frontend/src/lib/components/StockCard.svelte
> +		</div>
we dont need a buy and sell button in the profile, in the future we can add a link to the stock page

2024-02-06 17:28 UTC, quabey commented on frontend/src/lib/components/StockCard.svelte
> +<div
Please work on the layout and colors of the card 
![image](https://github.com/AtriEx/ATX/assets/50772988/1c6939c8-6ad4-4aa5-aeb9-7d80eb26536b)

2024-02-06 17:28 UTC, quabey commented on frontend/src/lib/components/ProfileBadge.svelte
> +			/>
Dont show the image only the text, show the image in the hovercard

2024-02-06 17:28 UTC, quabey commented on frontend/src/lib/components/ProfileComponent.svelte
> +			</div>
![image](https://github.com/AtriEx/ATX/assets/50772988/6d0ea5db-3cb8-4579-85dc-1e9e32e971e1)
Move the badges next to the username

2024-02-06 17:28 UTC, quabey commented on frontend/src/lib/components/ProfileComponent.svelte
> +				<span class="text-green-600">{formatNumber(balance)}</span>
drop the "current"

2024-02-21 05:37 UTC, quabey commented
Github webhook test

2024-03-13 01:23 UTC, RubenOlano commented on frontend/src/routes/profile/+layout.server.ts
> +	throw redirect(303, `/profile/${profile.username}`);
Can't seem to access the store within the server function. Not sure how to go about fixing this...

2024-03-13 01:25 UTC, RubenOlano commented
This also closes #55

2024-03-22 23:52 UTC, quabey commented
Looks great a few things that are missing: 

- [ ] Space between stocks and achievements in mobile view
![image](https://github.com/AtriEx/ATX/assets/50772988/252a019d-7627-4520-8ded-22ea24fa1af9)


- [ ] Clean up the data part in mobile view
![image](https://github.com/AtriEx/ATX/assets/50772988/c3f45bb5-6901-41d6-a9e8-e398be56562b)

- [ ]  Add error page when profile doesnt exists

2024-03-28 20:23 UTC, quabey requested changes

2024-03-28 20:23 UTC, quabey commented on frontend/src/routes/profile/[username]/+error.svelte
> +					on:click={() => history.back()}>Go back</button
This doesnt work, maybe just a redirect to "/"

2024-03-28 20:38 UTC, quabey commented
Comment

2024-03-28 21:18 UTC, quabey approved these changes

2024-03-28 21:19 UTC, merged