Website Header + Navigation
AtriEx/ATX pull request #9
Opened 2024-02-06 04:46 UTC by CraaazySteeeve

This PR includes:
A Header with:
- ATX Logo.
- Navigation options (only on Desktop, on mobile they are moved to the bottom of the screen)
- If the User isn't logged in:
- - A Twitch sign in button (Which isn't functional yet, as the login implementation will be done seperately)
- If the User IS logged in:
- - User currency/networth.
- - Username, and their PFP.
- - These user details are pull from a svelte store which could be updated with the details from the Twitch Login.

It DOES NOT include:
- The actual Twitch Login functionality.
- A daily login bonus button/functionality. (If it's decided this will be in the header, it can be added in a seperate ticket

2024-02-06 15:05 UTC, RubenOlano requested changes
I'd personally recommend removing the text from smaller screen buttons for navigation since they are self-explanatory. However you are free to overrule me on that call

2024-02-06 15:05 UTC, RubenOlano commented on frontend/src/lib/components/HeaderNavigationButton.svelte
> +        <span class="text-sm">{label}</span>
I'd recommend hiding text whenever in the mobile view since we're already using icons. Something like `class="hidden md:block text-sm"` in order to hide on smaller view

2024-02-06 15:05 UTC, RubenOlano commented on frontend/src/lib/components/HeaderUserView.svelte
> +        </svg>
Extract SVG into a searate component so its easier to tell what is going on

2024-02-06 15:05 UTC, RubenOlano commented on frontend/src/lib/components/MobileNavigationButton.svelte
> +        <span class="text-xs">{label}</span>
Something like class="hidden md:block text-sm" in order to hide on smaller view

2024-02-06 15:05 UTC, RubenOlano commented on frontend/src/lib/components/CurrencyView.svelte
> +    import {currency} from '$lib/stores/userData.js';
Minor nitpick but idk why this is importing as a `js` file rather than `ts`

2024-02-06 15:05 UTC, RubenOlano commented on frontend/src/lib/components/HeaderUserView.svelte
> +    import { isLoggedIn, username, userPfp} from '$lib/stores/userData.js';
Some here about `js` and `ts`

2024-02-06 15:36 UTC, sakulstar commented on frontend/src/lib/components/MobileNavigationButton.svelte
> +        <span class="text-xs">{label}</span>
[Explained it above](https://github.com/AtriEx/ATX/pull/9#discussion_r1480040913)

2024-02-06 15:40 UTC, sakulstar commented on frontend/src/lib/components/HeaderUserView.svelte
> +        </svg>
I don't think splitting them into separate SVG would simplify it, though I have noticed that changing the second value from true to false makes it less confusing, so I have committed those changes.

2024-02-07 01:52 UTC, CraaazySteeeve commented on frontend/src/lib/components/CurrencyView.svelte
> +    import {currency} from '$lib/stores/userData.js';
Resolved, removed 'js' extension.

2024-02-07 01:52 UTC, CraaazySteeeve commented on frontend/src/lib/components/HeaderUserView.svelte
> +    import { isLoggedIn, username, userPfp} from '$lib/stores/userData.js';
Resolved, removed 'js' extension.

2024-02-07 02:00 UTC, CraaazySteeeve commented
> I'd personally recommend removing the text from smaller screen buttons for navigation since they are self-explanatory. However you are free to overrule me on that call

I agree. I have modified the mobile buttons to be bigger, and removed the text.

2024-02-07 11:56 UTC, quabey approved these changes

2024-02-07 11:57 UTC, merged